version: '3.1'

services:

  db:
    image: ghusta/postgres-world-db 
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: world-db
      POSTGRES_USER: world
      POSTGRES_PASSWORD: world123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080